#!/bin/bash

# Determine Carbon Black Extension Type

cbVersion=$( defaults read /Applications/VMware\ Carbon\ Black\ Cloud/VMware\ CBCloud.app/Contents/Info.plist CFBundleVersion )

extensionStatus=$( /Applications/VMware\ Carbon\ Black\ Cloud/repcli.bundle/Contents/MacOS/repcli status | grep 'Kernel Type:' | awk '{ print $3, $4 }' )

if [[ $cbVersion == "3.5"* ]]; then
	echo "<result>$extensionStatus</result>"
else
	echo "<result>Kernel Extension</result>"
fi
